### ISSUE TITLE
Question - Custom resources meta.tag

### ISSUE THREAD

**Issue by rhinozD** [awslabs/fhir-works-on-aws-deployment#281] opened 2021-04-05 01:47 UTC
Hi AWS Team,
Thanks for implementing FHIR Works.
I want to add custom meta.tag when I POST a resource.
I just saw meta.lastUpdated and meta.versionId automatically generated after registration.
Does FHIR Works support custom meta.tag (and meta.security)? 
If already supported, please show me how to.

Thanks in advance for any help you are able to provide.

**Comment by rsmayda** [comment] 2021-04-05 18:13
We currently do not support additional meta elements but we are - Working on this now!

**Comment by rsmayda** [comment] 2021-04-05 18:15
Duplicate of: https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/60

**Closed as completed by rsmayda** 2021-04-05 18:15 UTC
Labels: duplicate, enhancement
